name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Typecheck & Build
        run: npm run build

      - name: Test (Jest)
        run: npm test -- --coverage

      - name: Package VSIX (dry run)
        run: npm run package:vsix

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload vsix (dry)
        uses: actions/upload-artifact@v4
        with:
          name: vsix-dry
          path: dist/extension.vsix
